import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "@/providers";
import { auth } from "@/auth";
export const metadata: Metadata = {
  title: "NextAuth-POC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = auth();
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <Header />
          {JSON.stringify(session)}
          <div className="px-3">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
